version: "3.8"

services:
  postgres:
    command: -c 'max_connections=200'
    image: postgres:16
    environment:
      POSTGRES_USER: mountaineer_billing
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mountaineer_billing_test_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
