# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from ._deferred import BaseModel, Field, RootModel

from ._internal import (
    CheckoutSessionPaymentMethodOptions,
    CheckoutSessionWalletOptions,
    CustomerModel,
    DeletedCustomer,
    InvoiceModel,
    Item,
    PaymentFlowsPaymentIntentPresentmentDetails,
)
from ._internal import PaymentIntent as PaymentIntent_1
from ._internal import PaymentLink as PaymentLink_1
from ._internal import (
    PaymentMethodConfigBizPaymentMethodConfigurationDetails,
    PaymentPagesCheckoutSessionAdaptivePricing,
    PaymentPagesCheckoutSessionAfterExpiration,
    PaymentPagesCheckoutSessionAutomaticTax,
    PaymentPagesCheckoutSessionCollectedInformation,
    PaymentPagesCheckoutSessionConsent,
    PaymentPagesCheckoutSessionConsentCollection,
    PaymentPagesCheckoutSessionCurrencyConversion,
    PaymentPagesCheckoutSessionCustomerDetails,
    PaymentPagesCheckoutSessionCustomFields,
    PaymentPagesCheckoutSessionCustomText,
    PaymentPagesCheckoutSessionDiscount,
    PaymentPagesCheckoutSessionInvoiceCreation,
    PaymentPagesCheckoutSessionOptionalItem,
    PaymentPagesCheckoutSessionPermissions,
    PaymentPagesCheckoutSessionPhoneNumberCollection,
    PaymentPagesCheckoutSessionSavedPaymentMethodOptions,
    PaymentPagesCheckoutSessionShippingAddressCollection,
    PaymentPagesCheckoutSessionShippingCost,
    PaymentPagesCheckoutSessionShippingOption,
    PaymentPagesCheckoutSessionTaxIdCollection,
    PaymentPagesCheckoutSessionTotalDetails,
)
from ._internal import SetupIntent as SetupIntent_1
from ._internal import SubscriptionModel


class BillingAddressCollection(StrEnum):
    auto = 'auto'
    required = 'required'


class Customer(RootModel[str | None]):
    root: Annotated[
        str | None,
        Field(
            description='The ID of the customer for this Session.\nFor Checkout Sessions in `subscription` mode or Checkout Sessions with `customer_creation` set as `always` in `payment` mode, Checkout\nwill create a new customer object based on information provided\nduring the payment flow unless an existing customer was provided when\nthe Session was created.',
            max_length=5000,
        ),
    ] = None


class CustomerCreation(StrEnum):
    always = 'always'
    if_required = 'if_required'


class Invoice(RootModel[str | None]):
    root: Annotated[
        str | None,
        Field(
            description='ID of the invoice created by the Checkout Session, if it exists.',
            max_length=5000,
        ),
    ] = None


class Object(StrEnum):
    list = 'list'


class Locale(StrEnum):
    auto = 'auto'
    bg = 'bg'
    cs = 'cs'
    da = 'da'
    de = 'de'
    el = 'el'
    en = 'en'
    en_GB = 'en-GB'
    es = 'es'
    es_419 = 'es-419'
    et = 'et'
    fi = 'fi'
    fil = 'fil'
    fr = 'fr'
    fr_CA = 'fr-CA'
    hr = 'hr'
    hu = 'hu'
    id = 'id'
    it = 'it'
    ja = 'ja'
    ko = 'ko'
    lt = 'lt'
    lv = 'lv'
    ms = 'ms'
    mt = 'mt'
    nb = 'nb'
    nl = 'nl'
    pl = 'pl'
    pt = 'pt'
    pt_BR = 'pt-BR'
    ro = 'ro'
    ru = 'ru'
    sk = 'sk'
    sl = 'sl'
    sv = 'sv'
    th = 'th'
    tr = 'tr'
    vi = 'vi'
    zh = 'zh'
    zh_HK = 'zh-HK'
    zh_TW = 'zh-TW'


class Mode(StrEnum):
    payment = 'payment'
    setup = 'setup'
    subscription = 'subscription'


MountaineerBillingApiVersion = Literal["2025-05-28.basil"]


class Object11Model(StrEnum):
    checkout_session = 'checkout.session'


class PaymentIntent(RootModel[str | None]):
    root: Annotated[
        str | None,
        Field(
            description="The ID of the PaymentIntent for Checkout Sessions in `payment` mode. You can't confirm or cancel the PaymentIntent for a Checkout Session. To cancel, [expire the Checkout Session](https://stripe.com/docs/api/checkout/sessions/expire) instead.",
            max_length=5000,
        ),
    ] = None


class PaymentLink(RootModel[str | None]):
    root: Annotated[
        str | None,
        Field(
            description='The ID of the Payment Link that created this Session.',
            max_length=5000,
        ),
    ] = None


class PaymentMethodCollection(StrEnum):
    always = 'always'
    if_required = 'if_required'


class PaymentMethodType(RootModel[str]):
    root: Annotated[str, Field(max_length=5000)]


class PaymentStatus(StrEnum):
    no_payment_required = 'no_payment_required'
    paid = 'paid'
    unpaid = 'unpaid'


class RedirectOnCompletion(StrEnum):
    always = 'always'
    if_required = 'if_required'
    never = 'never'


class SetupIntent(RootModel[str | None]):
    root: Annotated[
        str | None,
        Field(
            description="The ID of the SetupIntent for Checkout Sessions in `setup` mode. You can't confirm or cancel the SetupIntent for a Checkout Session. To cancel, [expire the Checkout Session](https://stripe.com/docs/api/checkout/sessions/expire) instead.",
            max_length=5000,
        ),
    ] = None


class Status(StrEnum):
    complete = 'complete'
    expired = 'expired'
    open = 'open'


class SubmitType(StrEnum):
    auto = 'auto'
    book = 'book'
    donate = 'donate'
    pay = 'pay'
    subscribe = 'subscribe'


class Subscription(RootModel[str | None]):
    root: Annotated[
        str | None,
        Field(
            description='The ID of the [Subscription](https://stripe.com/docs/api/subscriptions) for Checkout Sessions in `subscription` mode.',
            max_length=5000,
        ),
    ] = None


class UiMode(StrEnum):
    custom = 'custom'
    embedded = 'embedded'
    hosted = 'hosted'


class LineItems(BaseModel):
    data: Annotated[list[Item], Field(description='Details about each object.')]
    has_more: Annotated[
        bool,
        Field(
            description='True if this list has another page of items after this one that can be fetched.'
        ),
    ]
    object: Annotated[
        Object,
        Field(
            description="String representing the object's type. Objects of the same type share the same value. Always has the value `list`."
        ),
    ]
    url: Annotated[
        str,
        Field(description='The URL where this list can be accessed.', max_length=5000),
    ]


class Session(BaseModel):
    adaptive_pricing: Annotated[
        PaymentPagesCheckoutSessionAdaptivePricing | None,
        Field(
            description='Settings for price localization with [Adaptive Pricing](https://docs.stripe.com/payments/checkout/adaptive-pricing).'
        ),
    ] = None
    after_expiration: Annotated[
        PaymentPagesCheckoutSessionAfterExpiration | None,
        Field(
            description='When set, provides configuration for actions to take if this Checkout Session expires.'
        ),
    ] = None
    allow_promotion_codes: Annotated[
        bool | None, Field(description='Enables user redeemable promotion codes.')
    ] = None
    amount_subtotal: Annotated[
        int | None,
        Field(description='Total of all items before discounts or taxes are applied.'),
    ] = None
    amount_total: Annotated[
        int | None,
        Field(description='Total of all items after discounts and taxes are applied.'),
    ] = None
    automatic_tax: PaymentPagesCheckoutSessionAutomaticTax
    billing_address_collection: Annotated[
        BillingAddressCollection | None,
        Field(
            description="Describes whether Checkout should collect the customer's billing address. Defaults to `auto`."
        ),
    ] = None
    cancel_url: Annotated[
        str | None,
        Field(
            description='If set, Checkout displays a back button and customers will be directed to this URL if they decide to cancel payment and return to your website.',
            max_length=5000,
        ),
    ] = None
    client_reference_id: Annotated[
        str | None,
        Field(
            description='A unique string to reference the Checkout Session. This can be a\ncustomer ID, a cart ID, or similar, and can be used to reconcile the\nSession with your internal systems.',
            max_length=5000,
        ),
    ] = None
    client_secret: Annotated[
        str | None,
        Field(
            description='The client secret of your Checkout Session. Applies to Checkout Sessions with `ui_mode: embedded` or `ui_mode: custom`. For `ui_mode: embedded`, the client secret is to be used when initializing Stripe.js embedded checkout.\n For `ui_mode: custom`, use the client secret with [initCheckout](https://stripe.com/docs/js/custom_checkout/init) on your front end.',
            max_length=5000,
        ),
    ] = None
    collected_information: Annotated[
        PaymentPagesCheckoutSessionCollectedInformation | None,
        Field(
            description='Information about the customer collected within the Checkout Session.'
        ),
    ] = None
    consent: Annotated[
        PaymentPagesCheckoutSessionConsent | None,
        Field(description='Results of `consent_collection` for this session.'),
    ] = None
    consent_collection: Annotated[
        PaymentPagesCheckoutSessionConsentCollection | None,
        Field(
            description='When set, provides configuration for the Checkout Session to gather active consent from customers.'
        ),
    ] = None
    created: Annotated[
        int,
        Field(
            description='Time at which the object was created. Measured in seconds since the Unix epoch.'
        ),
    ]
    currency: Annotated[
        str | None,
        Field(
            description='Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).'
        ),
    ] = None
    currency_conversion: Annotated[
        PaymentPagesCheckoutSessionCurrencyConversion | None,
        Field(
            description='Currency conversion details for [Adaptive Pricing](https://docs.stripe.com/payments/checkout/adaptive-pricing) sessions created before 2025-03-31.'
        ),
    ] = None
    custom_fields: Annotated[
        list[PaymentPagesCheckoutSessionCustomFields],
        Field(
            description='Collect additional information from your customer using custom fields. Up to 3 fields are supported.'
        ),
    ]
    custom_text: PaymentPagesCheckoutSessionCustomText
    customer: Annotated[
        Customer | CustomerModel | DeletedCustomer | None,
        Field(
            description='The ID of the customer for this Session.\nFor Checkout Sessions in `subscription` mode or Checkout Sessions with `customer_creation` set as `always` in `payment` mode, Checkout\nwill create a new customer object based on information provided\nduring the payment flow unless an existing customer was provided when\nthe Session was created.'
        ),
    ] = None
    customer_creation: Annotated[
        CustomerCreation | None,
        Field(
            description='Configure whether a Checkout Session creates a Customer when the Checkout Session completes.'
        ),
    ] = None
    customer_details: Annotated[
        PaymentPagesCheckoutSessionCustomerDetails | None,
        Field(
            description="The customer details including the customer's tax exempt status and the customer's tax IDs. Customer's address details are not present on Sessions in `setup` mode."
        ),
    ] = None
    customer_email: Annotated[
        str | None,
        Field(
            description='If provided, this value will be used when the Customer object is created.\nIf not provided, customers will be asked to enter their email address.\nUse this parameter to prefill customer data if you already have an email\non file. To access information about the customer once the payment flow is\ncomplete, use the `customer` attribute.',
            max_length=5000,
        ),
    ] = None
    discounts: Annotated[
        list[PaymentPagesCheckoutSessionDiscount] | None,
        Field(
            description='List of coupons and promotion codes attached to the Checkout Session.'
        ),
    ] = None
    expires_at: Annotated[
        int,
        Field(description='The timestamp at which the Checkout Session will expire.'),
    ]
    id: Annotated[
        str, Field(description='Unique identifier for the object.', max_length=5000)
    ]
    invoice: Annotated[
        Invoice | InvoiceModel | None,
        Field(
            description='ID of the invoice created by the Checkout Session, if it exists.'
        ),
    ] = None
    invoice_creation: Annotated[
        PaymentPagesCheckoutSessionInvoiceCreation | None,
        Field(
            description='Details on the state of invoice creation for the Checkout Session.'
        ),
    ] = None
    line_items: Annotated[
        LineItems | None,
        Field(
            description='The line items purchased by the customer.',
            title='PaymentPagesCheckoutSessionListLineItems',
        ),
    ] = None
    livemode: Annotated[
        bool,
        Field(
            description='Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.'
        ),
    ]
    locale: Annotated[
        Locale | None,
        Field(
            description="The IETF language tag of the locale Checkout is displayed in. If blank or `auto`, the browser's locale is used."
        ),
    ] = None
    metadata: Annotated[
        dict[str, str] | None,
        Field(
            description='Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.'
        ),
    ] = None
    mode: Annotated[Mode, Field(description='The mode of the Checkout Session.')]
    mountaineer_billing_api_version: MountaineerBillingApiVersion
    object: Annotated[
        Object11Model,
        Field(
            description="String representing the object's type. Objects of the same type share the same value."
        ),
    ]
    optional_items: Annotated[
        list[PaymentPagesCheckoutSessionOptionalItem] | None,
        Field(description='The optional items presented to the customer at checkout.'),
    ] = None
    payment_intent: Annotated[
        PaymentIntent | PaymentIntent_1 | None,
        Field(
            description="The ID of the PaymentIntent for Checkout Sessions in `payment` mode. You can't confirm or cancel the PaymentIntent for a Checkout Session. To cancel, [expire the Checkout Session](https://stripe.com/docs/api/checkout/sessions/expire) instead."
        ),
    ] = None
    payment_link: Annotated[
        PaymentLink | PaymentLink_1 | None,
        Field(description='The ID of the Payment Link that created this Session.'),
    ] = None
    payment_method_collection: Annotated[
        PaymentMethodCollection | None,
        Field(
            description='Configure whether a Checkout Session should collect a payment method. Defaults to `always`.'
        ),
    ] = None
    payment_method_configuration_details: Annotated[
        PaymentMethodConfigBizPaymentMethodConfigurationDetails | None,
        Field(
            description='Information about the payment method configuration used for this Checkout session if using dynamic payment methods.'
        ),
    ] = None
    payment_method_options: Annotated[
        CheckoutSessionPaymentMethodOptions | None,
        Field(
            description='Payment-method-specific configuration for the PaymentIntent or SetupIntent of this CheckoutSession.'
        ),
    ] = None
    payment_method_types: Annotated[
        list[PaymentMethodType],
        Field(
            description='A list of the types of payment methods (e.g. card) this Checkout\nSession is allowed to accept.'
        ),
    ]
    payment_status: Annotated[
        PaymentStatus,
        Field(
            description="The payment status of the Checkout Session, one of `paid`, `unpaid`, or `no_payment_required`.\nYou can use this value to decide when to fulfill your customer's order."
        ),
    ]
    permissions: Annotated[
        PaymentPagesCheckoutSessionPermissions | None,
        Field(
            description='This property is used to set up permissions for various actions (e.g., update) on the CheckoutSession object.\n\nFor specific permissions, please refer to their dedicated subsections, such as `permissions.update_shipping_details`.'
        ),
    ] = None
    phone_number_collection: PaymentPagesCheckoutSessionPhoneNumberCollection | None = (
        None
    )
    presentment_details: PaymentFlowsPaymentIntentPresentmentDetails | None = None
    recovered_from: Annotated[
        str | None,
        Field(
            description='The ID of the original expired Checkout Session that triggered the recovery flow.',
            max_length=5000,
        ),
    ] = None
    redirect_on_completion: Annotated[
        RedirectOnCompletion | None,
        Field(
            description='This parameter applies to `ui_mode: embedded`. Learn more about the [redirect behavior](https://stripe.com/docs/payments/checkout/custom-success-page?payment-ui=embedded-form) of embedded sessions. Defaults to `always`.'
        ),
    ] = None
    return_url: Annotated[
        str | None,
        Field(
            description="Applies to Checkout Sessions with `ui_mode: embedded` or `ui_mode: custom`. The URL to redirect your customer back to after they authenticate or cancel their payment on the payment method's app or site.",
            max_length=5000,
        ),
    ] = None
    saved_payment_method_options: Annotated[
        PaymentPagesCheckoutSessionSavedPaymentMethodOptions | None,
        Field(
            description='Controls saved payment method settings for the session. Only available in `payment` and `subscription` mode.'
        ),
    ] = None
    setup_intent: Annotated[
        SetupIntent | SetupIntent_1 | None,
        Field(
            description="The ID of the SetupIntent for Checkout Sessions in `setup` mode. You can't confirm or cancel the SetupIntent for a Checkout Session. To cancel, [expire the Checkout Session](https://stripe.com/docs/api/checkout/sessions/expire) instead."
        ),
    ] = None
    shipping_address_collection: Annotated[
        PaymentPagesCheckoutSessionShippingAddressCollection | None,
        Field(
            description='When set, provides configuration for Checkout to collect a shipping address from a customer.'
        ),
    ] = None
    shipping_cost: Annotated[
        PaymentPagesCheckoutSessionShippingCost | None,
        Field(
            description='The details of the customer cost of shipping, including the customer chosen ShippingRate.'
        ),
    ] = None
    shipping_options: Annotated[
        list[PaymentPagesCheckoutSessionShippingOption],
        Field(description='The shipping rate options applied to this Session.'),
    ]
    status: Annotated[
        Status | None,
        Field(
            description='The status of the Checkout Session, one of `open`, `complete`, or `expired`.'
        ),
    ] = None
    submit_type: Annotated[
        SubmitType | None,
        Field(
            description='Describes the type of transaction being performed by Checkout in order to customize\nrelevant text on the page, such as the submit button. `submit_type` can only be\nspecified on Checkout Sessions in `payment` mode. If blank or `auto`, `pay` is used.'
        ),
    ] = None
    subscription: Annotated[
        Subscription | SubscriptionModel | None,
        Field(
            description='The ID of the [Subscription](https://stripe.com/docs/api/subscriptions) for Checkout Sessions in `subscription` mode.'
        ),
    ] = None
    success_url: Annotated[
        str | None,
        Field(
            description='The URL the customer will be directed to after the payment or\nsubscription creation is successful.',
            max_length=5000,
        ),
    ] = None
    tax_id_collection: PaymentPagesCheckoutSessionTaxIdCollection | None = None
    total_details: Annotated[
        PaymentPagesCheckoutSessionTotalDetails | None,
        Field(description='Tax and discount details for the computed total amount.'),
    ] = None
    ui_mode: Annotated[
        UiMode | None,
        Field(description='The UI mode of the Session. Defaults to `hosted`.'),
    ] = None
    url: Annotated[
        str | None,
        Field(
            description='The URL to the Checkout Session. Applies to Checkout Sessions with `ui_mode: hosted`. Redirect customers to this URL to take them to Checkout. If you’re using [Custom Domains](https://stripe.com/docs/payments/checkout/custom-domains), the URL will use your subdomain. Otherwise, it’ll use `checkout.stripe.com.`\nThis value is only present when the session is active.',
            max_length=5000,
        ),
    ] = None
    wallet_options: Annotated[
        CheckoutSessionWalletOptions | None,
        Field(description='Wallet-specific configuration for this Checkout Session.'),
    ] = None
