# generated by datamodel-codegen:
#   filename:  schema.json

from ._internal import Object_3 as Object
from ._internal import Status_2 as Status
from ._internal import TestClock_2 as TestClock

__all__ = ["Object", "Status", "TestClock"]
