# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from ._deferred import BaseModel, Field


class Object(StrEnum):
    test_helpers_test_clock = 'test_helpers.test_clock'


class Status(StrEnum):
    advancing = 'advancing'
    internal_failure = 'internal_failure'
    ready = 'ready'


class TestClock(BaseModel):
    created: Annotated[
        int,
        Field(
            description='Time at which the object was created. Measured in seconds since the Unix epoch.'
        ),
    ]
    deletes_after: Annotated[
        int, Field(description='Time at which this clock is scheduled to auto delete.')
    ]
    frozen_time: Annotated[
        int,
        Field(
            description='Time at which all objects belonging to this clock are frozen.'
        ),
    ]
    id: Annotated[
        str, Field(description='Unique identifier for the object.', max_length=5000)
    ]
    livemode: Annotated[
        bool,
        Field(
            description='Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.'
        ),
    ]
    name: Annotated[
        str | None,
        Field(description='The custom name supplied at creation.', max_length=5000),
    ] = None
    object: Annotated[
        Object,
        Field(
            description="String representing the object's type. Objects of the same type share the same value."
        ),
    ]
    status: Annotated[Status, Field(description='The status of the Test Clock.')]
